version: "3.8"

networks:
  main-network:

services:
  mysql:
    container_name: mysql_express
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql.env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - main-network
